name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: ${{ matrix.os }} Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies (Ubuntu)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y cmake build-essential
        # Build and install GTest from source
        sudo apt-get install -y libgtest-dev
        cd /usr/src/gtest
        sudo cmake CMakeLists.txt
        sudo make
        sudo cp lib/*.a /usr/lib
        cd -

    - name: Install Dependencies (macOS)
      if: runner.os == 'macOS'
      run: |
        brew install cmake
        # Build and install GTest from source
        git clone https://github.com/google/googletest.git
        cd googletest
        cmake -B build -DCMAKE_BUILD_TYPE=Release
        cmake --build build --config Release
        sudo cmake --install build
        cd ..

    - name: Configure CMake
      run: |
        cmake -B build \
          -DCMAKE_BUILD_TYPE=${{ matrix.build_type }} \
          -DBUILD_TESTS=ON \
          -DCMAKE_CXX_FLAGS="-mavx2"

    - name: Build
      run: cmake --build build --config ${{ matrix.build_type }}

    - name: Run Tests
      working-directory: build
      run: |
        ctest -C ${{ matrix.build_type }} --output-on-failure

    - name: Run Demo
      working-directory: build
      run: ./examples/demo 