name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  rocky9-build:
    name: Rocky Linux 9 Build
    runs-on: ubuntu-latest
    container: rockylinux/rockylinux:9

    strategy:
      matrix:
        build_type: [Release, Debug]

    steps:
    - uses: actions/checkout@v3

    - name: Install Dependencies
      run: |
        dnf -y update
        dnf -y install dnf-plugins-core epel-release
        dnf -y config-manager --set-enabled crb
        dnf -y groupinstall "Development Tools"
        dnf -y install \
          cmake \
          gcc-c++ \
          make \
          git \
          ninja-build \
          python3 \
          python3-pip

    - name: Configure CMake
      run: |
        cmake -B build -DCMAKE_BUILD_TYPE=${{matrix.build_type}} -DBUILD_TESTS=ON

    - name: Build
      run: cmake --build build --config ${{matrix.build_type}}

    - name: Test
      working-directory: build
      run: ctest -C ${{matrix.build_type}} --output-on-failure

    - name: Run Demo
      working-directory: build
      run: ./examples/demo
